# spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true
# spring.datasource.username=root
# spring.datasource.password=Rakshitha@123
# spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:h2:mem:ecommerce_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rakshithamatti123@gmail.com
spring.mail.password=kogyhvyfyvutacot
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

razorpay.key.id=rzp_test_SkQv1EbdOKpYMH
razorpay.key.secret=y83ihWjJxeluZ1DDKJqR6B4m

cloudinary.cloud.name=duyadzw4p
cloudinary.api.key=781855564433973
cloudinary.api.secret=8lkH08o_k_405ZTLc5_x8pY38Rw